version: "3.4"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  x-app: &base-app
    build:
      context: .
      target: app
    depends_on:
      - database
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./deploy:/app/deploy
      - ./pyproject.toml:/app/pyproject.toml
    environment: &base-app-env
      SECRET_KEY: "insecure"
      DEBUG: "true"
    entrypoint: /app/deploy/wait-for-it.sh database:5432 --

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8000

  app:
    <<: *base-app
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION
    image: docker-registry.data.amsterdam.nl/datapunt/tellus:${VERSION:-latest}
    command: /app/deploy/docker-run.sh

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
      PYTEST_ADDOPTS:
