version: "3.0"
services:
  database:
    image: amsterdam/postgres
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: tellus
      POSTGRES_USER: tellus
      POSTGRES_PASSWORD: insecure

  web:
    build: ./web
    ports:
      - "8107:8000"
    links:
      - database
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      - SECRET_KEY=hoi
      - DATABASE_NAME=tellus
      - DATABASE_USER=tellus
      - DATABASE_PASSWORD=insecure
      - TELLUS_OBJECTSTORE_PASSWORD=insecure
      - CONSUL_HOST=${CONSUL_HOST:-notset}
      - CONSUL_PORT=${CONSUL_PORT:-8500}
      - UWSGI_HTTP="0.0.0.0:8000"
      - UWSGI_MODULE=tellus.wsgi:application
      - UWSGI_MASTER=1
      - UWSGI_STATIC_MAP=/static=/static
      - JWT_SHARED_SECRET_KEY=${JWT_SHARED_SECRET_KEY:-insecureinsecureinsecure}
