version: "3.0"
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5409:5432"
    environment:
      POSTGRES_DB: tellus
      POSTGRES_USER: tellus
      POSTGRES_PASSWORD: insecure

  web:
    build: ./web
    ports:
      - "8107:8000"
    links:
      - database
    environment:
      - DATAPUNT_API_URL=${DATAPUNT_API_URL:-https://api.datapunt.amsterdam.nl/}
      - SECRET_KEY=hoi
      - DATABASE_NAME=tellus
      - DATABASE_USER=tellus
      - DATABASE_PASSWORD=insecure
      - TELLUS_OBJECTSTORE_PASSWORD=insecure
      - CONSUL_HOST=${CONSUL_HOST:-notset}
      - CONSUL_PORT=${CONSUL_PORT:-8500}
