version: 3.0
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: tellus

  tests:
    build: ../web
    links:
      - database
    environment:
      DATABASE_NAME: tellus
      DATABASE_USER: tellus
      DATABASE_PASSWORD: insecure
    command: >
      bash -c "cd /app && ./docker-code-check.sh && ./docker-test.sh"
