version: "3.0"
services:
  database:
    image: amsterdam/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: tellus
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: build.datapunt.amsterdam.nl:5000/datapunt/tellus:${ENVIRONMENT}
    links:
      - database
    environment:
      TELLUS_OBJECTSTORE_PASSWORD:
      DATABASE_NAME: tellus
      DATABASE_USER: tellus
      DATABASE_PASSWORD: insecure
      DATABASE_HOST_OVERRIDE: database
      DATABASE_PORT_OVERRIDE: 5432
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
    volumes:
      - ./backups/elasticsearch:/tmp/backups
    command: >
      bash -c "/app/docker-wait.sh \
              && python manage.py migrate \
              && export DJANGO_SETTINGS_MODULE=tellus.settings \
              && python importer.py\
              && python import_validator.py
