version: "3.4"
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: tellus
      POSTGRES_DB: tellus
    volumes:
      - ./backups:/tmp/backups

  importer:
    image: docker-registry.data.amsterdam.nl/datapunt/tellus:${ENVIRONMENT}
    depends_on:
      - database
    environment:
      TELLUS_OBJECTSTORE_PASSWORD:
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      DJANGO_SETTINGS_MODULE: main.settings
      DATABASE_NAME: tellus
      DATABASE_USER: tellus
      DATABASE_PASSWORD: insecure
    command: /app/deploy/import/import-run.sh
