swagger: "2.0"

info:
  version: 1.0.0
  title: Tellus API
  description: The tellus Rest API

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

securityDefinitions:
  OAuth2:
    type: oauth2
    description: 'Authorization through datapunt Authorization service. Scopes start with GREX for this API'
    authorizationUrl: '/oauth2/authorize'
    flow: implicit
    scopes:
      TLLS/R: Read tellus

paths:
  /tellus/tellus:
    get:
      description: Returns tellus objects
      produces:
        - application/json
      parameters:
        -
          name: page
          in: query
          description: Page number to view
          required: false
          default: 1
          type: integer
          format: int64
        -
          name: page_size
          in: query
          description: number of rows per page
          required: false
          default: 100
          type: integer
          format: int64
        -
          name: lat
          in: query
          description: latitude of viewpoint
          required: false
          default: 0.0
          type: number
          format: float
        -
          name: lon
          in: query
          description: longitude of viewpoint
          required: false
          default: 0
          type: number
          format: float
        -
          name: radius
          in: query
          description: radius of viewpoint
          required: false
          default: 25
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            type: array
            items:
              $ref: "#/definitions/Tellus"

  /tellus/tellus/{id}:
    get:
      description: Returns a Tellus based on a single ID
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        -
          name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Tellus not found
        "200":
          description: request successful
          schema:
            $ref: '#/definitions/Tellus'

  /tellus/tellusdata/:
    get:
      description: Returns tellus measurements per hour
      security:
        - OAuth2:
            - TLLS/R
      produces:
        - application/json
      parameters:
        -
          name: page
          in: query
          description: Page number to view
          required: false
          default: 1
          type: integer
          format: int64
        -
          name: page_size
          in: query
          description: number of rows per page
          required: false
          default: 100
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            type: array
            items:
              $ref: "#/definitions/TellusData"

  /tellus/telusdata/{id}:
    get:
      description: Returns a tellus data object for id
      security:
        - OAuth2:
            - TLLS/R
      produces:
        - application/json

      parameters:
        -
          name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            $ref: "#/definitions/TellusData"

  /tellus/lengtecategorie:
    get:
      description: Returns a list of lengte categorie objects
      produces:
        - application/json
      parameters:
        -
          name: page
          in: query
          description: Page number to view
          required: false
          default: 1
          type: integer
          format: int64
        -
          name: page_size
          in: query
          description: number of rows per page
          required: false
          default: 100
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            type: array
            items:
              $ref: "#/definitions/LengteCategorie"
  /tellus/lengtecategorie/{klasse}:
    get:
      description: Return lengtecategorie with class {klasse}
      parameters:
        -
          name: klasse
          in: path
          description: Class of the lengtecategorie object
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            $ref: "#/definitions/LengteCategorie"

  /tellus/snelheidscategorie:
    get:
      description: Returns a list of snelheids categorie objects
      produces:
        - application/json
      parameters:
        -
          name: page
          in: query
          description: Page number to view
          required: false
          default: 1
          type: integer
          format: int64
        -
          name: page_size
          in: query
          description: number of rows per page
          required: false
          default: 100
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            type: array
            items:
              $ref: "#/definitions/SnelheidsCategorie"

  /tellus/snelheidscategorie/{klasse}:
    get:
      description: Return snelheidscategorie with class {klasse}
      parameters:
        -
          name: klasse
          in: path
          description: class of snelheidscategorie
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: 404 not found
        "200":
          description: request successful
          schema:
            $ref: "#/definitions/SnelheidsCategorie"

definitions:
  LengteCategorie:
    type: object
    required:
      - klasse
    properties:
      klasse:
        type: integer
      l1:
        type: string
      l2:
        type: string
      l3:
        type: string
      l4:
        type: string
      l5:
        type: string
      l6:
        type: string

  SnelheidsCategorie:
    type: object
    required:
      - klasse
    properties:
      klasse:
        type: integer
      s1:
        type: string
      s2:
        type: string
      s3:
        type: string
      s4:
        type: string
      s5:
        type: string
      s6:
        type: string
      s7:
        type: string
      s8:
        type: string
      s9:
        type: string
      s10:
        type: string

  Tellus:
    type: object
    required:
      - id
      - snelheids_klasse
    properties:
      id:
        type: integer
      objnr_vor:
        type: string
      objnr_leverancier:
        type: string
      snelheids_klasse:
        $ref: "#/definitions/SnelheidsCategorie"
      standplaats:
        type: string
      zijstraat_a:
        type: string
      zijstraat_b:
        type: string
      richting_1:
        type: string
      richting_2:
        type: string
      latitude:
        type: number
        format: float
      longitude:
        type: number
        format: float
      rijksdriehoek_x:
        type: number
        format: float
      rijksdriehoek_y:
        type: number
        format: float
      geometrie:
        type: string
      _display:
        type: string

  TellusData:
    type: object
    required:
      - id
      - tellus
      - snelheids_categorie
      - lengte_categorie
    properties:
      id:
        type: integer
      tellus:
        $ref: "#/definitions/Tellus"
      snelheids_categorie:
        $ref: "#/definitions/SnelheidsCategorie"
      lengte_categorie:
        $ref: "#/definitions/LengteCategorie"
      tijd_van:
        type: string
        format: date-time
      tijd_tot:
        type: string
        format: date-time
      richting:
        type: integer
      validatie:
        type: integer
      representatief:
        type: integer
      meetraai:
        type: integer
      meetresultatem:
        type: string
      _display:
        type: string
